In [1]:
import pandas as pd

scientists = pd.DataFrame(
    data={
        "Occupation": ["Chemist", "Statistician"],
        "Born": ["1920-07-25", "1876-06-13"],
        "Died": ["1958-04-16", "1937-10-16"],
        "Age": [37, 61],
    },
    index=["Rosaline Franklin", "William Gosset"],
    columns=["Occupation", "Born", "Died", "Age"],
)
print(scientists)

                     Occupation        Born        Died  Age
Rosaline Franklin       Chemist  1920-07-25  1958-04-16   37
William Gosset     Statistician  1876-06-13  1937-10-16   61

In [22]:
scientists.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Rosaline Franklin to William Gosset
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Occupation  2 non-null      object
 1   Born        2 non-null      object
 2   Died        2 non-null      object
 3   Age         2 non-null      int64
dtypes: int64(1), object(3)
memory usage: 80.0+ bytes

In [23]:
scientists['born_dt'] = pd.to_datetime( scientists['Born'],format='%Y-%m-%d' )

In [24]:
scientists['died_dt'] = pd.to_datetime( scientists['Died'],format='%Y-%m-%d' )

In [25]:
scientists.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Rosaline Franklin to William Gosset
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Occupation  2 non-null      object
 1   Born        2 non-null      object
 2   Died        2 non-null      object
 3   Age         2 non-null      int64
 4   born_dt     2 non-null      datetime64[ns]
 5   died_dt     2 non-null      datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 112.0+ bytes

In [27]:
#생존날짜 계산
scientists['age_days'] = scientists['died_dt']-scientists['born_dt']

In [28]:
scientists

,Occupation,Born,Died,Age,born_dt,died_dt,age_days
Rosaline Franklin,Chemist,1920-07-25,1958-04-16,37,1920-07-25,1958-04-16,13779 days
William Gosset,Statistician,1876-06-13,1937-10-16,61,1876-06-13,1937-10-16,22404 days

In [45]:
scientists.info()       #datetime칼럼만 갖고 있는 속성 .dt(시리즈 내에 있는 값에 반복적으로 계산해주는 변수)

<class 'pandas.core.frame.DataFrame'>
Index: 2 entries, Rosaline Franklin to William Gosset
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Occupation  2 non-null      object
 1   Born        2 non-null      object
 2   Died        2 non-null      object
 3   Age         2 non-null      int64
 4   born_dt     2 non-null      datetime64[ns]
 5   died_dt     2 non-null      datetime64[ns]
 6   age_days    2 non-null      timedelta64[ns]
 7   age_years   2 non-null      float64
dtypes: datetime64[ns](2), float64(1), int64(1), object(3), timedelta64[ns](1)
memory usage: 252.0+ bytes

In [43]:
import numpy as np

scientists['age_years'] = (scientists['age_days'].dt.days/365).apply(np.floor) #버림(소수점 이하) 반복적으로 처리:apply

In [42]:
scientists

,Occupation,Born,Died,Age,born_dt,died_dt,age_days,age_years
Rosaline Franklin,Chemist,1920-07-25,1958-04-16,37,1920-07-25,1958-04-16,13779 days,37.0
William Gosset,Statistician,1876-06-13,1937-10-16,61,1876-06-13,1937-10-16,22404 days,61.0

In [49]:
df_dropped = scientists.drop('Age', axis='columns') #'Age'가 어느 행(axis)에 있느냐 입력 필수
# scientists = scientists.drop('Age', axis='columns') # 원본 반영
# scientists.drop('Age',axis='columns', inplace=True) # 얘가 훨씬 빠름

In [50]:
whos

Variable               Type         Data/Info
---------------------------------------------
dataframe_columns      function     <function dataframe_colum<...>ns at 0x000001DCCCE9FA60>
dataframe_hash         function     <function dataframe_hash at 0x000001DCCCE9D4E0>
df_dropped             DataFrame    Shape: (2, 7)
dtypes_str             function     <function dtypes_str at 0x000001DCCCE9C900>
get_dataframes         function     <function get_dataframes at 0x000001DCCCE9D440>
getpass                module       <module 'getpass' from 'C<...>conda3\\Lib\\getpass.py'>
hashlib                module       <module 'hashlib' from 'C<...>conda3\\Lib\\hashlib.py'>
import_pandas_safely   function     <function import_pandas_s<...>ly at 0x000001DCCCDCE700>
is_data_frame          function     <function is_data_frame at 0x000001DCCCDCE840>
json                   module       <module 'json' from 'C:\\<...>\Lib\\json\\__init__.py'>
np                     module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
pd                     module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
scientists             DataFrame    Shape: (2, 8)

In [52]:
scientists['Occupation'].str.upper()

Rosaline Franklin         CHEMIST
William Gosset       STATISTICIAN
Name: Occupation, dtype: object

In [54]:
def my_sq(x):
    '''
    입력 파라미터를 제공하는 함수
    '''
    return x**2

In [56]:
df = pd.DataFrame({
    'a':[10,20,30],
    'b':[20,30,40],
})
df

    a   b
0  10  20
1  20  30
2  30  40

In [66]:
def my_sq(x):
    print('x=',x)
    return x**2

df['a'].apply(my_sq)

x= 10
x= 20
x= 30

0    100
1    400
2    900
Name: a, dtype: int64

In [67]:
def to_grade(x):
    if x == 10: return "A"
    if x == 20: return "B"
    return "C"

df['a'].apply(to_grade)

0    A
1    B
2    C
Name: a, dtype: object