In [6]:
import pandas as pd
import matplotlib.pyplot as plt

plt.rc('font',family='Malgun Gothic')

file='./data/LOCAL_PEOPLE_DONG_202603.csv'
df = pd.read_csv(file,usecols=range(32)) # 강제로 읽을 칼럼 지정해서 갯수 제한

In [7]:
df

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20260301,0,11110515,14865.8552,578.9309,368.8959,467.0917,478.6377,418.0992,419.2893,...,358.4801,563.1438,657.8919,709.5855,774.9088,696.4526,594.3021,520.2162,312.3586,1049.8964
1,20260301,0,11110530,11026.4936,298.0482,132.4658,176.0656,276.5370,374.3473,374.6543,...,401.4622,428.9179,530.7341,533.6079,577.5174,498.6681,475.7923,379.3442,251.1412,790.2839
2,20260301,0,11110540,3606.3990,67.6455,51.8324,108.8807,394.9549,176.7948,125.9931,...,91.7097,103.4282,128.2236,151.0100,160.8298,136.8064,107.5852,116.8247,94.9865,252.7907
3,20260301,0,11110550,11103.0331,271.3521,210.4024,394.8536,316.0689,334.7137,228.8648,...,287.2671,348.1848,411.4859,530.4120,491.5882,489.8839,561.4703,379.9948,344.2910,968.6910
4,20260301,0,11110560,19482.2034,585.1147,423.2326,504.1146,750.9308,413.2591,404.7132,...,494.8888,495.1996,734.2611,796.9016,1011.8118,954.6015,997.1770,891.8163,622.9984,1742.2362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315451,20260331,23,11680590,35450.1598,1566.4079,1045.7849,1258.8818,820.1925,1055.9423,1164.9600,...,1305.6608,1405.2127,1784.8832,1907.0999,2379.7648,1505.6163,1117.3760,736.0760,532.0845,1605.3502
315452,20260331,23,11680600,29821.7566,1440.9634,2004.9857,2441.7662,501.7368,359.9368,262.4763,...,381.8346,294.4643,789.4791,1650.8642,2400.9526,1317.8301,714.4692,521.9938,422.6761,1191.4814
315453,20260331,23,11680610,36949.8235,1527.6196,2198.9634,2679.1547,767.7366,665.5806,801.3564,...,664.0717,766.3727,1152.3360,1875.8942,2782.3679,1576.9510,1058.1635,853.5227,671.2697,2007.3645
315454,20260331,23,11680630,30950.3995,1000.3998,1097.1462,1907.4485,867.4211,1045.8652,1127.4775,...,1179.0314,1025.3496,1267.4501,1432.4982,1781.8008,1423.5696,1029.8829,640.9563,419.6904,975.9495
315455,20260331,23,11680640,68784.4643,812.7575,353.9425,1148.4912,2028.7459,3932.6195,4507.8850,...,5112.7551,4509.9535,4335.3635,3218.9986,2753.4105,1991.8958,1452.6410,1248.8713,829.3506,2122.8915

엑셀파일 칼럼수와 데이터프레임 칼럼수가 다름...

In [3]:
a='"기준일ID","시간대구분","행정동코드","총생활인구수","남자0세부터9세생활인구수","남자10세부터14세생활인구수","남자15세부터19세생활인구수","남자20세부터24세생활인구수","남자25세부터29세생활인구수","남자30세부터34세생활인구수","남자35세부터39세생활인구수","남자40세부터44세생활인구수","남자45세부터49세생활인구수","남자50세부터54세생활인구수","남자55세부터59세생활인구수","남자60세부터64세생활인구수","남자65세부터69세생활인구수","남자70세이상생활인구수","여자0세부터9세생활인구수","여자10세부터14세생활인구수","여자15세부터19세생활인구수","여자20세부터24세생활인구수","여자25세부터29세생활인구수","여자30세부터34세생활인구수","여자35세부터39세생활인구수","여자40세부터44세생활인구수","여자45세부터49세생활인구수","여자50세부터54세생활인구수","여자55세부터59세생활인구수","여자60세부터64세생활인구수","여자65세부터69세생활인구수","여자70세이상생활인구수"'
len(a.split(','))

32

In [16]:
df.query('기준일ID == 20260301 and 시간대구분 == 0')

,기준일ID,시간대구분,행정동코드,총생활인구수,남자0세부터9세생활인구수,남자10세부터14세생활인구수,남자15세부터19세생활인구수,남자20세부터24세생활인구수,남자25세부터29세생활인구수,남자30세부터34세생활인구수,...,여자25세부터29세생활인구수,여자30세부터34세생활인구수,여자35세부터39세생활인구수,여자40세부터44세생활인구수,여자45세부터49세생활인구수,여자50세부터54세생활인구수,여자55세부터59세생활인구수,여자60세부터64세생활인구수,여자65세부터69세생활인구수,여자70세이상생활인구수
0,20260301,0,11110515,14865.8552,578.9309,368.8959,467.0917,478.6377,418.0992,419.2893,...,358.4801,563.1438,657.8919,709.5855,774.9088,696.4526,594.3021,520.2162,312.3586,1049.8964
1,20260301,0,11110530,11026.4936,298.0482,132.4658,176.0656,276.5370,374.3473,374.6543,...,401.4622,428.9179,530.7341,533.6079,577.5174,498.6681,475.7923,379.3442,251.1412,790.2839
2,20260301,0,11110540,3606.3990,67.6455,51.8324,108.8807,394.9549,176.7948,125.9931,...,91.7097,103.4282,128.2236,151.0100,160.8298,136.8064,107.5852,116.8247,94.9865,252.7907
3,20260301,0,11110550,11103.0331,271.3521,210.4024,394.8536,316.0689,334.7137,228.8648,...,287.2671,348.1848,411.4859,530.4120,491.5882,489.8839,561.4703,379.9948,344.2910,968.6910
4,20260301,0,11110560,19482.2034,585.1147,423.2326,504.1146,750.9308,413.2591,404.7132,...,494.8888,495.1996,734.2611,796.9016,1011.8118,954.6015,997.1770,891.8163,622.9984,1742.2362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,20260301,0,11740650,26179.5129,1143.0506,396.5097,532.3860,586.9353,1026.4470,1129.1417,...,1294.7768,1181.5321,1241.5475,926.0501,976.9960,930.7166,978.7068,946.6132,759.1043,1953.8016
420,20260301,0,11740660,29640.7003,760.0823,456.8848,806.3005,892.9551,1109.4328,1109.0752,...,1248.6498,1300.8218,1347.1784,1145.4156,1451.3505,1110.2466,1259.1114,1023.5534,840.3491,2279.3365
421,20260301,0,11740685,61005.6699,1914.1731,925.6292,1129.5585,1415.0016,2217.7094,2288.6770,...,2605.6235,2403.4894,2880.4980,2228.3160,2544.5257,2407.7870,2527.1552,2314.5570,1852.3699,4872.1346
422,20260301,0,11740690,33902.6264,1734.7400,1314.7549,938.9692,573.0757,556.9243,802.1095,...,698.5573,1046.9582,1608.7299,2043.0995,1585.5914,1160.3117,1198.3705,1148.3108,848.0759,2493.6200
423,20260301,0,11740700,25836.1439,1115.1861,562.5603,706.0556,625.6457,728.5280,832.0642,...,878.8901,903.6370,1100.6177,1079.9682,1163.4798,934.6937,1106.6544,929.4933,691.6451,1984.2057

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 315456 entries, 0 to 315455
Data columns (total 32 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   기준일ID            315456 non-null  int64
 1   시간대구분            315456 non-null  int64
 2   행정동코드            315456 non-null  int64
 3   총생활인구수           315456 non-null  float64
 4   남자0세부터9세생활인구수    315456 non-null  float64
 5   남자10세부터14세생활인구수  315456 non-null  float64
 6   남자15세부터19세생활인구수  315456 non-null  float64
 7   남자20세부터24세생활인구수  315456 non-null  float64
 8   남자25세부터29세생활인구수  315456 non-null  float64
 9   남자30세부터34세생활인구수  315456 non-null  float64
 10  남자35세부터39세생활인구수  315456 non-null  float64
 11  남자40세부터44세생활인구수  315456 non-null  float64
 12  남자45세부터49세생활인구수  315456 non-null  float64
 13  남자50세부터54세생활인구수  315456 non-null  float64
 14  남자55세부터59세생활인구수  315456 non-null  float64
 15  남자60세부터64세생활인구수  315456 non-null  float64
 16  남자65세부터69세생활인구수  315456 non-null  float64
 17  남자70세이상생활인구수     315456 non-null  float64
 18  여자0세부터9세생활인구수    315456 non-null  float64
 19  여자10세부터14세생활인구수  315456 non-null  float64
 20  여자15세부터19세생활인구수  315456 non-null  float64
 21  여자20세부터24세생활인구수  315456 non-null  float64
 22  여자25세부터29세생활인구수  315456 non-null  float64
 23  여자30세부터34세생활인구수  315456 non-null  float64
 24  여자35세부터39세생활인구수  315456 non-null  float64
 25  여자40세부터44세생활인구수  315456 non-null  float64
 26  여자45세부터49세생활인구수  315456 non-null  float64
 27  여자50세부터54세생활인구수  315456 non-null  float64
 28  여자55세부터59세생활인구수  315456 non-null  float64
 29  여자60세부터64세생활인구수  315456 non-null  float64
 30  여자65세부터69세생활인구수  315456 non-null  float64
 31  여자70세이상생활인구수     315456 non-null  float64
dtypes: float64(29), int64(3)
memory usage: 77.0 MB