In [1]:
import pandas as pd
df = pd.read_excel('./data/apt_seoul.xlsx',skiprows=12,thousands=",")

C:\Users\User\anaconda3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

#전처리 과정
1. 아파트데이터 분할(시,군,구)
2. 거래금액 단위 변환(억단위)
3. 번지, 본번, 부번 제거
4. 전용면적 제곱미터 -> 평으로 변환
5. 해제사유발생일에 값이 있는 행을 삭제
6. 계약년월로 요일을 구하여 요일별 가격(요일칼럼 추가)

In [2]:
df

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 은평구 수색동,416-1,416,1,DMC 진흥,78.2853,202604,4,77500,...,15,개인,개인,2003,은평터널로 60,-,중개거래,서울 은평구,-,아파트
1,2,서울특별시 서대문구 북가좌동,481,481,0,DMC래미안e편한세상,153.8600,202604,3,165000,...,8,개인,개인,2012,수색로 100,-,직거래,-,-,아파트
2,3,서울특별시 서대문구 대현동,144,144,0,신촌럭키,59.7000,202604,3,120000,...,13,개인,개인,1999,이화여대길 50-12,-,중개거래,서울 서대문구,-,아파트
3,4,서울특별시 성동구 성수동1가,708,708,0,동아그린,58.3200,202604,3,135000,...,12,개인,개인,1999,상원길 76,-,중개거래,서울 성동구,-,아파트
4,5,서울특별시 송파구 잠실동,22,22,0,리센츠,84.9900,202604,3,350000,...,11,개인,개인,2008,올림픽로 135,-,중개거래,서울 송파구,-,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76661,76662,서울특별시 성북구 하월곡동,222,222,0,월곡두산위브,84.8430,202504,7,81800,...,9,개인,개인,2003,오패산로 46,-,중개거래,서울 성북구,25.06.16,아파트
76662,76663,서울특별시 동대문구 장안동,580,580,0,장안위더스빌,84.8500,202504,7,77800,...,16,개인,개인,2011,한천로 42,-,중개거래,서울 동대문구,25.07.22,아파트
76663,76664,서울특별시 성북구 안암동1가,361,361,0,안암동삼성래미안,59.6983,202504,7,76000,...,6,개인,개인,2005,고려대로17가길 64,-,중개거래,서울 성북구,25.06.16,아파트
76664,76665,서울특별시 성북구 정릉동,780,780,0,"산장아파트가동,나동",52.8900,202504,7,30000,...,1,개인,개인,1977,보국문로 167,-,중개거래,서울 성북구,25.06.30,아파트
76665,76666,서울특별시 중랑구 신내동,650,650,0,신내6대주,39.8400,202504,7,40500,...,12,개인,개인,1996,신내로19길 42,-,중개거래,서울 중랑구,25.07.15,아파트

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76666 entries, 0 to 76665
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NO        76666 non-null  int64
 1   시군구       76666 non-null  object
 2   번지        76666 non-null  object
 3   본번        76666 non-null  int64
 4   부번        76666 non-null  int64
 5   단지명       76666 non-null  object
 6   전용면적(㎡)   76666 non-null  float64
 7   계약년월      76666 non-null  int64
 8   계약일       76666 non-null  int64
 9   거래금액(만원)  76666 non-null  int64
 10  동         76666 non-null  object
 11  층         76666 non-null  int64
 12  매수자       76666 non-null  object
 13  매도자       76666 non-null  object
 14  건축년도      76666 non-null  int64
 15  도로명       76666 non-null  object
 16  해제사유발생일   76666 non-null  object
 17  거래유형      76666 non-null  object
 18  중개사소재지    76666 non-null  object
 19  등기일자      76666 non-null  object
 20  주택유형      76666 non-null  object
dtypes: float64(1), int64(8), object(12)
memory usage: 12.3+ MB

In [4]:
df.loc[[ 3 ]]

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
3,4,서울특별시 성동구 성수동1가,708,708,0,동아그린,58.32,202604,3,135000,...,12,개인,개인,1999,상원길 76,-,중개거래,서울 성동구,-,아파트

In [5]:
sum(df['단지명'].str.contains('선사현대'))
r1 = df['단지명'].str.contains('선사현대')
df.loc[ r1 ]

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
936,937,서울특별시 강동구 암사동,509,509,0,선사현대아파트,59.64,202603,21,137500,...,8,개인,개인,2000,상암로 11,-,중개거래,"서울 강동구, 서울 송파구",-,아파트
3058,3059,서울특별시 강동구 암사동,509,509,0,선사현대아파트,59.64,202603,6,143900,...,28,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,26.03.20,아파트
4180,4181,서울특별시 강동구 암사동,509,509,0,선사현대아파트,82.94,202602,27,200000,...,15,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,-,아파트
4643,4644,서울특별시 강동구 암사동,509,509,0,선사현대아파트,59.64,202602,25,144000,...,3,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,-,아파트
5340,5341,서울특별시 강동구 암사동,509,509,0,선사현대아파트,59.64,202602,21,144500,...,2,개인,개인,2000,상암로 11,-,중개거래,"서울 강동구, 서울 송파구",-,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76129,76130,서울특별시 강동구 암사동,509,509,0,선사현대아파트,83.67,202504,10,127000,...,14,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,25.05.16,아파트
76130,76131,서울특별시 강동구 암사동,509,509,0,선사현대아파트,83.79,202504,10,122000,...,16,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,25.07.10,아파트
76315,76316,서울특별시 강동구 암사동,509,509,0,선사현대아파트,59.64,202504,9,104000,...,10,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,25.06.27,아파트
76316,76317,서울특별시 강동구 암사동,509,509,0,선사현대아파트,72.85,202504,9,113000,...,21,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,25.06.20,아파트
76457,76458,서울특별시 강동구 암사동,509,509,0,선사현대아파트,72.85,202504,8,113800,...,14,개인,개인,2000,상암로 11,-,중개거래,서울 강동구,25.07.02,아파트

In [6]:
df.describe()

,NO,본번,부번,전용면적(㎡),계약년월,계약일,거래금액(만원),층,건축년도
count,76666.000000,76666.000000,76666.000000,76666.000000,76666.000000,76666.000000,7.666600e+04,76666.000000,76666.00000
mean,38333.500000,639.730924,4.548327,75.265764,202526.253359,16.450187,1.201652e+05,9.585670,2003.25032
std,22131.712206,632.316776,39.419937,27.371606,37.503080,8.523682,8.870981e+04,6.375242,11.33792
min,1.000000,1.000000,0.000000,11.330000,202504.000000,1.000000,6.500000e+03,-2.000000,1961.00000
25%,19167.250000,257.250000,0.000000,59.750100,202506.000000,10.000000,6.800000e+04,5.000000,1996.00000
50%,38333.500000,510.000000,0.000000,79.980000,202509.000000,17.000000,9.850000e+04,9.000000,2003.00000
75%,57499.750000,822.000000,0.000000,84.960000,202512.000000,24.000000,1.470000e+05,13.000000,2012.00000
max,76666.000000,4974.000000,2837.000000,317.360000,202604.000000,31.000000,2.900000e+06,66.000000,2025.00000

In [7]:
df.head()

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 은평구 수색동,416-1,416,1,DMC 진흥,78.2853,202604,4,77500,...,15,개인,개인,2003,은평터널로 60,-,중개거래,서울 은평구,-,아파트
1,2,서울특별시 서대문구 북가좌동,481,481,0,DMC래미안e편한세상,153.8600,202604,3,165000,...,8,개인,개인,2012,수색로 100,-,직거래,-,-,아파트
2,3,서울특별시 서대문구 대현동,144,144,0,신촌럭키,59.7000,202604,3,120000,...,13,개인,개인,1999,이화여대길 50-12,-,중개거래,서울 서대문구,-,아파트
3,4,서울특별시 성동구 성수동1가,708,708,0,동아그린,58.3200,202604,3,135000,...,12,개인,개인,1999,상원길 76,-,중개거래,서울 성동구,-,아파트
4,5,서울특별시 송파구 잠실동,22,22,0,리센츠,84.9900,202604,3,350000,...,11,개인,개인,2008,올림픽로 135,-,중개거래,서울 송파구,-,아파트

In [8]:
df.tail()

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
76661,76662,서울특별시 성북구 하월곡동,222,222,0,월곡두산위브,84.8430,202504,7,81800,...,9,개인,개인,2003,오패산로 46,-,중개거래,서울 성북구,25.06.16,아파트
76662,76663,서울특별시 동대문구 장안동,580,580,0,장안위더스빌,84.8500,202504,7,77800,...,16,개인,개인,2011,한천로 42,-,중개거래,서울 동대문구,25.07.22,아파트
76663,76664,서울특별시 성북구 안암동1가,361,361,0,안암동삼성래미안,59.6983,202504,7,76000,...,6,개인,개인,2005,고려대로17가길 64,-,중개거래,서울 성북구,25.06.16,아파트
76664,76665,서울특별시 성북구 정릉동,780,780,0,"산장아파트가동,나동",52.8900,202504,7,30000,...,1,개인,개인,1977,보국문로 167,-,중개거래,서울 성북구,25.06.30,아파트
76665,76666,서울특별시 중랑구 신내동,650,650,0,신내6대주,39.8400,202504,7,40500,...,12,개인,개인,1996,신내로19길 42,-,중개거래,서울 중랑구,25.07.15,아파트

In [9]:
# 계약년월별 계약건수 - count(). 건수는 행갯수라서 아무 칼럼 선택
df.groupby('계약년월')['층'].count().sort_values() #오름차순
df.groupby('계약년월')['층'].count().sort_values(ascending=False) #내림차순

계약년월
202506    12611
202509     9080
202510     8941
202505     8560
202602     5851
202601     5496
202512     4916
202504     4704
202507     4635
202508     4612
202603     3676
202511     3519
202604       65
Name: 층, dtype: int64

In [10]:
#층별 건수
df.groupby('층')['층'].count().sort_values()

층
-2        1
 63       1
 61       1
 60       1
 59       1
       ...
 6     4775
 7     4822
 4     4912
 3     4938
 5     5117
Name: 층, Length: 65, dtype: int64

In [11]:
# df.['전용면적(㎡)'].plot(kind='box')

In [12]:
df.isna()

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76661,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76662,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76663,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76664,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
76665,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isna().sum() #결측값 존재X

NO          0
시군구         0
번지          0
본번          0
부번          0
단지명         0
전용면적(㎡)     0
계약년월        0
계약일         0
거래금액(만원)    0
동           0
층           0
매수자         0
매도자         0
건축년도        0
도로명         0
해제사유발생일     0
거래유형        0
중개사소재지      0
등기일자        0
주택유형        0
dtype: int64

In [14]:
print(df['거래금액(만원)'].mean())
print(df['거래금액(만원)'].max())
df['거래금액(만원)'].min()

120165.15651005661
2900000

6500

In [33]:
df['구'] = df['시군구'].str.split().str[1] #구
df['동'] = df['시군구'].str.split().str[2] #동
# df['시군구'].str.split().str.get(2)

In [45]:
# 구별 거래건수
df.groupby('구')['구'].count() #인덱스 기준 정렬
df.groupby('구')['구'].count().sort_values() #값 기준 정렬
df.groupby('구')['구'].count().sort_values(ascending=False) #내림차순 정렬

구
노원구     6458
강동구     4876
강서구     4684
성북구     4606
송파구     4402
영등포구    4182
구로구     3932
동대문구    3855
성동구     3693
동작구     3543
마포구     3447
양천구     3444
서대문구    3284
은평구     3209
강남구     2964
관악구     2431
중랑구     2296
서초구     2055
도봉구     2036
광진구     1810
강북구     1373
용산구     1257
중구      1179
금천구     1013
종로구      637
Name: 구, dtype: int64

In [43]:
#구별 평균 거래 금액
df.groupby('구')['거래금액(만원)'].mean().sort_values(ascending=False)

구
강남구     287236.284076
서초구     254540.297324
용산구     202541.906126
송파구     187292.982962
성동구     163180.646900
마포구     147786.690746
광진구     142495.504420
양천구     133742.825203
동작구     131640.912504
영등포구    127093.447633
강동구     127036.664479
종로구     118438.783359
중구      117052.372349
서대문구    104578.360536
동대문구     93076.965759
강서구      88652.402007
성북구      87700.336083
은평구      84336.634154
관악구      83309.753188
구로구      69344.506358
강북구      65903.758194
중랑구      65342.369338
금천구      64330.769990
노원구      63596.164447
도봉구      56021.716601
Name: 거래금액(만원), dtype: float64

In [47]:
# 전용면적 -> 평 전용면적 / 3.3
df['평'] = df['전용면적(㎡)']/3.3
# 구별 평 평균
df.groupby('구')['평'].mean().sort_values(ascending=False)

구
서초구     28.273607
강남구     26.123427
용산구     25.966743
송파구     25.043769
동작구     24.655565
양천구     24.114041
광진구     24.052006
성동구     23.949617
종로구     23.840930
마포구     23.546907
영등포구    23.097311
서대문구    23.069582
중구      22.935836
강동구     22.921605
성북구     22.841498
관악구     22.621216
동대문구    21.961434
은평구     21.732617
강북구     21.730504
금천구     21.620579
강서구     21.264590
중랑구     20.858122
도봉구     20.665682
구로구     20.588597
노원구     19.109502
Name: 평, dtype: float64

In [49]:
df.groupby?

Signature:
df.groupby(
    by=None,
    axis: 'Axis | lib.NoDefault' = <no_default>,
    level: 'IndexLabel | None' = None,
    as_index: 'bool' = True,
    sort: 'bool' = True,
    group_keys: 'bool' = True,
    observed: 'bool | lib.NoDefault' = <no_default>,
    dropna: 'bool' = True,
) -> 'DataFrameGroupBy'
Docstring:
Group DataFrame using a mapper or by a Series of columns.

A groupby operation involves some combination of splitting the
object, applying a function, and combining the results. This can be
used to group large amounts of data and compute operations on these
groups.

Parameters
----------
by : mapping, function, label, pd.Grouper or list of such
    Used to determine the groups for the groupby.
    If ``by`` is a function, it's called on each value of the object's
    index. If a dict or Series is passed, the Series or dict VALUES
    will be used to determine the groups (the Series' values are first
    aligned; see ``.align()`` method). If a list or ndarray of length
    equal to the selected axis is passed (see the `groupby user guide
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#splitting-an-object-into-groups>`_),
    the values are used as-is to determine the groups. A label or list
    of labels may be passed to group by the columns in ``self``.
    Notice that a tuple is interpreted as a (single) key.
axis : {0 or 'index', 1 or 'columns'}, default 0
    Split along rows (0) or columns (1). For `Series` this parameter
    is unused and defaults to 0.

    .. deprecated:: 2.1.0

        Will be removed and behave like axis=0 in a future version.
        For ``axis=1``, do ``frame.T.groupby(...)`` instead.

level : int, level name, or sequence of such, default None
    If the axis is a MultiIndex (hierarchical), group by a particular
    level or levels. Do not specify both ``by`` and ``level``.
as_index : bool, default True
    Return object with group labels as the
    index. Only relevant for DataFrame input. as_index=False is
    effectively "SQL-style" grouped output. This argument has no effect
    on filtrations (see the `filtrations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
    such as ``head()``, ``tail()``, ``nth()`` and in transformations
    (see the `transformations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).
sort : bool, default True
    Sort group keys. Get better performance by turning this off.
    Note this does not influence the order of observations within each
    group. Groupby preserves the order of rows within each group. If False,
    the groups will appear in the same order as they did in the original DataFrame.
    This argument has no effect on filtrations (see the `filtrations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#filtration>`_),
    such as ``head()``, ``tail()``, ``nth()`` and in transformations
    (see the `transformations in the user guide
    <https://pandas.pydata.org/docs/dev/user_guide/groupby.html#transformation>`_).

    .. versionchanged:: 2.0.0

        Specifying ``sort=False`` with an ordered categorical grouper will no
        longer sort the values.

group_keys : bool, default True
    When calling apply and the ``by`` argument produces a like-indexed
    (i.e. :ref:`a transform <groupby.transform>`) result, add group keys to
    index to identify pieces. By default group keys are not included
    when the result's index (and column) labels match the inputs, and
    are included otherwise.

    .. versionchanged:: 1.5.0

       Warns that ``group_keys`` will no longer be ignored when the
       result from ``apply`` is a like-indexed Series or DataFrame.
       Specify ``group_keys`` explicitly to include the group keys or
       not.

    .. versionchanged:: 2.0.0

       ``group_keys`` now defaults to ``True``.

observed : bool, default False
    This only applies if any of the groupers are Categoricals.
    If True: only show observed values for categorical groupers.
    If False: show all values for categorical groupers.

    .. deprecated:: 2.1.0

        The default value will change to True in a future version of pandas.

dropna : bool, default True
    If True, and if group keys contain NA values, NA values together
    with row/column will be dropped.
    If False, NA values will also be treated as the key in groups.

Returns
-------
pandas.api.typing.DataFrameGroupBy
    Returns a groupby object that contains information about the groups.

See Also
--------
resample : Convenience method for frequency conversion and resampling
    of time series.

Notes
-----
See the `user guide
<https://pandas.pydata.org/pandas-docs/stable/groupby.html>`__ for more
detailed usage and examples, including splitting an object into groups,
iterating through groups, selecting a group, aggregation, and more.

Examples
--------
>>> df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
...                               'Parrot', 'Parrot'],
...                    'Max Speed': [380., 370., 24., 26.]})
>>> df
   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0
>>> df.groupby(['Animal']).mean()
        Max Speed
Animal
Falcon      375.0
Parrot       25.0

**Hierarchical Indexes**

We can groupby different levels of a hierarchical index
using the `level` parameter:

>>> arrays = [['Falcon', 'Falcon', 'Parrot', 'Parrot'],
...           ['Captive', 'Wild', 'Captive', 'Wild']]
>>> index = pd.MultiIndex.from_arrays(arrays, names=('Animal', 'Type'))
>>> df = pd.DataFrame({'Max Speed': [390., 350., 30., 20.]},
...                   index=index)
>>> df
                Max Speed
Animal Type
Falcon Captive      390.0
       Wild         350.0
Parrot Captive       30.0
       Wild          20.0
>>> df.groupby(level=0).mean()
        Max Speed
Animal
Falcon      370.0
Parrot       25.0
>>> df.groupby(level="Type").mean()
         Max Speed
Type
Captive      210.0
Wild         185.0

We can also choose to include NA in group keys or not by setting
`dropna` parameter, the default setting is `True`.

>>> l = [[1, 2, 3], [1, None, 4], [2, 1, 3], [1, 2, 2]]
>>> df = pd.DataFrame(l, columns=["a", "b", "c"])

>>> df.groupby(by=["b"]).sum()
    a   c
b
1.0 2   3
2.0 2   5

>>> df.groupby(by=["b"], dropna=False).sum()
    a   c
b
1.0 2   3
2.0 2   5
NaN 1   4

>>> l = [["a", 12, 12], [None, 12.3, 33.], ["b", 12.3, 123], ["a", 1, 1]]
>>> df = pd.DataFrame(l, columns=["a", "b", "c"])

>>> df.groupby(by="a").sum()
    b     c
a
a   13.0   13.0
b   12.3  123.0

>>> df.groupby(by="a", dropna=False).sum()
    b     c
a
a   13.0   13.0
b   12.3  123.0
NaN 12.3   33.0

When using ``.apply()``, use ``group_keys`` to include or exclude the
group keys. The ``group_keys`` argument defaults to ``True`` (include).

>>> df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
...                               'Parrot', 'Parrot'],
...                    'Max Speed': [380., 370., 24., 26.]})
>>> df.groupby("Animal", group_keys=True)[['Max Speed']].apply(lambda x: x)
          Max Speed
Animal
Falcon 0      380.0
       1      370.0
Parrot 2       24.0
       3       26.0

>>> df.groupby("Animal", group_keys=False)[['Max Speed']].apply(lambda x: x)
   Max Speed
0      380.0
1      370.0
2       24.0
3       26.0
File:      c:\users\user\anaconda3\lib\site-packages\pandas\core\frame.py
Type:      method

In [51]:
df['평']

0        23.722818
1        46.624242
2        18.090909
3        17.672727
4        25.754545
           ...
76661    25.710000
76662    25.712121
76663    18.090394
76664    16.027273
76665    12.072727
Name: 평, Length: 76666, dtype: float64

In [53]:
# 평을 평형으로
def to_ph(x):
    if x < 10: return "10평이하"
    if x < 20: return "10평대"
    if x < 30: return "20평대"
    if x < 40: return "30평대"
    return "40평이상"

df['평형'] = df['평'].apply(to_ph)

In [59]:
#평형별 평균 거래금액
df.groupby('평형')['거래금액(만원)'].mean()

평형
10평대      91128.868047
10평이하     29249.800058
20평대     130019.064870
30평대     174648.563887
40평이상    289218.165863
Name: 거래금액(만원), dtype: float64

In [66]:
#평형별 거래건수
df.groupby('평형')['평형'].count()

평형
10평대     30420
10평이하     3446
20평대     32357
30평대      7748
40평이상     2695
Name: 평형, dtype: int64

In [61]:
#평형별 최고거래금액
df.groupby('평형')['거래금액(만원)'].max()

평형
10평대      560000
10평이하     181800
20평대      720000
30평대      920000
40평이상    2900000
Name: 거래금액(만원), dtype: int64

In [68]:
#평형별 최고평
df.groupby('평형')['평'].max()

평형
10평대     19.978788
10평이하     9.993939
20평대     29.999818
30평대     39.993939
40평이상    96.169697
Name: 평, dtype: float64

In [69]:
#구별 평형별 거래건수
df.groupby(['구','평형'])['층'].count()

구    평형
강남구  10평대      935
     10평이하      92
     20평대     1063
     30평대      513
     40평이상     361
              ...
중랑구  10평대      931
     10평이하     176
     20평대     1002
     30평대      169
     40평이상      18
Name: 층, Length: 124, dtype: int64

In [87]:
#전체 평균 거래금액에 가장 가까운 거래금액의 아파트를 찾으세요
a = df['거래금액(만원)'].mean()
df['diff'] = (df['거래금액(만원)'] - a).abs()
df.sort_values('diff').head()

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형,시,구,평,평형,diff
41210,41211,서울특별시 은평구 수색동,417,417,0,DMC롯데캐슬더퍼스트,84.97,202509,3,120200,...,-,중개거래,서울 은평구,25.09.23,아파트,서울특별시,은평구,25.748485,20평대,34.84349
26336,26337,서울특별시 동대문구 회기동,351,351,0,회기힐스테이트,120.31,202510,17,120200,...,-,직거래,-,25.10.29,아파트,서울특별시,동대문구,36.457576,30평대,34.84349
58803,58804,서울특별시 강동구 둔촌동,630,630,0,둔촌푸르지오,59.98,202506,14,120300,...,-,중개거래,서울 강동구,25.10.27,아파트,서울특별시,강동구,18.175758,10평대,134.84349
20340,20341,서울특별시 양천구 신정동,337,337,0,목동우성2,113.91,202511,28,120000,...,-,중개거래,서울 양천구,26.02.23,아파트,서울특별시,양천구,34.518182,30평대,165.15651
54538,54539,서울특별시 성동구 마장동,818,818,0,현대,134.79,202506,23,120000,...,-,중개거래,서울 성동구,25.07.25,아파트,서울특별시,성동구,40.845455,40평이상,165.15651

In [104]:
#해제사유방생일에 값이 있는 행을 삭제
b1 = df['해제사유발생일'] != "-" #거래취소된 행
len(df[b1]) #행갯수
df[b1] #거래취소된 행만 추출
# df[b1].count #모든 칼럼별 행갯수

b1 = df['해제사유발생일'] == "-" #거래정상처리된 행
len(df[b1]) #행갯수
df2 = df[b1] #거래정상처리된 행만 추출

In [106]:
print(df['계약년월'][0], df['계약일'][0])

202604 4

In [108]:
df['계약년월'].astype(str) + df['계약일'].astype(str).str.zfill(2) #()자릿수의 공백자리를 zero로 fill채운다

0        20260404
1        20260403
2        20260403
3        20260403
4        20260403
           ...
76661    20250407
76662    20250407
76663    20250407
76664    20250407
76665    20250407
Length: 76666, dtype: object

day_name()은 요일이 영어로 나옴. 이걸 한글로 바꾸기 위해 .map을 사용ㄱ

In [105]:
#계약년월 + 계약일 -> 요일칼럼추가
df['계약일자'] = pd.to_datetime(
    df['계약년월'].astype(str) + df['계약일'].astype(str).str.zfill(2),
    format='%Y%m%d'
)

df['요일'] = df['계약일자'].dt.day_name().map({
    'Monday': '월', 'Tuesday': '화', 'Wednesday': '수',
    'Thursday': '목', 'Friday': '금', 'Saturday': '토', 'Sunday': '일'
})
df

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,중개사소재지,등기일자,주택유형,시,구,평,평형,diff,계약일자,요일
0,1,서울특별시 은평구 수색동,416-1,416,1,DMC 진흥,78.2853,202604,4,77500,...,서울 은평구,-,아파트,서울특별시,은평구,23.722818,20평대,42665.15651,2026-04-04,토
1,2,서울특별시 서대문구 북가좌동,481,481,0,DMC래미안e편한세상,153.8600,202604,3,165000,...,-,-,아파트,서울특별시,서대문구,46.624242,40평이상,44834.84349,2026-04-03,금
2,3,서울특별시 서대문구 대현동,144,144,0,신촌럭키,59.7000,202604,3,120000,...,서울 서대문구,-,아파트,서울특별시,서대문구,18.090909,10평대,165.15651,2026-04-03,금
3,4,서울특별시 성동구 성수동1가,708,708,0,동아그린,58.3200,202604,3,135000,...,서울 성동구,-,아파트,서울특별시,성동구,17.672727,10평대,14834.84349,2026-04-03,금
4,5,서울특별시 송파구 잠실동,22,22,0,리센츠,84.9900,202604,3,350000,...,서울 송파구,-,아파트,서울특별시,송파구,25.754545,20평대,229834.84349,2026-04-03,금
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76661,76662,서울특별시 성북구 하월곡동,222,222,0,월곡두산위브,84.8430,202504,7,81800,...,서울 성북구,25.06.16,아파트,서울특별시,성북구,25.710000,20평대,38365.15651,2025-04-07,월
76662,76663,서울특별시 동대문구 장안동,580,580,0,장안위더스빌,84.8500,202504,7,77800,...,서울 동대문구,25.07.22,아파트,서울특별시,동대문구,25.712121,20평대,42365.15651,2025-04-07,월
76663,76664,서울특별시 성북구 안암동1가,361,361,0,안암동삼성래미안,59.6983,202504,7,76000,...,서울 성북구,25.06.16,아파트,서울특별시,성북구,18.090394,10평대,44165.15651,2025-04-07,월
76664,76665,서울특별시 성북구 정릉동,780,780,0,"산장아파트가동,나동",52.8900,202504,7,30000,...,서울 성북구,25.06.30,아파트,서울특별시,성북구,16.027273,10평대,90165.15651,2025-04-07,월
76665,76666,서울특별시 중랑구 신내동,650,650,0,신내6대주,39.8400,202504,7,40500,...,서울 중랑구,25.07.15,아파트,서울특별시,중랑구,12.072727,10평대,79665.15651,2025-04-07,월

In [115]:
#요일별 거래건수
df.groupby('요일')['요일'].count().sort_values(ascending=False)

요일
토    17809
금    13357
수    11199
목    10650
화    10395
월     9387
일     3869
Name: 요일, dtype: int64

In [113]:
#요일별 평균거래금액
df.groupby('요일')['거래금액(만원)'].mean().round()

요일
금    125190.0
목    118841.0
수    119057.0
월    118973.0
일    116588.0
토    118074.0
화    122251.0
Name: 거래금액(만원), dtype: float64

In [117]:
df.sort_values('단지명')

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,중개사소재지,등기일자,주택유형,시,구,평,평형,diff,계약일자,요일
47434,47435,서울특별시 성동구 행당동,1-10,1,10,(1-10),75.70,202507,20,46000,...,-,25.08.19,아파트,서울특별시,성동구,22.939394,20평대,74165.15651,2025-07-20,일
11538,11539,서울특별시 영등포구 대림동,1101-1,1101,1,(1101-1),14.81,202601,23,10800,...,서울 영등포구,26.02.13,아파트,서울특별시,영등포구,4.487879,10평이하,109365.15651,2026-01-23,금
76090,76091,서울특별시 영등포구 대림동,1101-1,1101,1,(1101-1),13.90,202504,10,10900,...,서울 영등포구,25.04.16,아파트,서울특별시,영등포구,4.212121,10평이하,109265.15651,2025-04-10,목
17857,17858,서울특별시 영등포구 대림동,1101-1,1101,1,(1101-1),13.90,202512,13,10300,...,서울 영등포구,26.01.07,아파트,서울특별시,영등포구,4.212121,10평이하,109865.15651,2025-12-13,토
47887,47888,서울특별시 영등포구 대림동,1101-1,1101,1,(1101-1),14.46,202507,17,12500,...,-,25.07.17,아파트,서울특별시,영등포구,4.381818,10평이하,107665.15651,2025-07-17,목
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72073,72074,서울특별시 금천구 독산동,894-5,894,5,힐탑아파트4차(894-5),54.90,202504,30,32000,...,서울 금천구,25.06.20,아파트,서울특별시,금천구,16.636364,10평대,88165.15651,2025-04-30,수
27061,27062,서울특별시 양천구 신정동,1305,1305,0,힐탑이루미,80.64,202510,15,59130,...,서울 양천구,26.01.20,아파트,서울특별시,양천구,24.436364,20평대,61035.15651,2025-10-15,수
51831,51832,서울특별시 양천구 신정동,1305,1305,0,힐탑이루미,81.08,202506,27,57500,...,서울 양천구,25.09.22,아파트,서울특별시,양천구,24.569697,20평대,62665.15651,2025-06-27,금
6901,6902,서울특별시 용산구 한남동,1-44,1,44,힐탑트레져1동,182.85,202602,12,400000,...,서울 용산구,-,아파트,서울특별시,용산구,55.409091,40평이상,279834.84349,2026-02-12,목
3996,3997,서울특별시 용산구 후암동,244-91,244,91,힐튼빌리지1차,100.83,202602,28,128000,...,서울 용산구,-,아파트,서울특별시,용산구,30.554545,30평대,7834.84349,2026-02-28,토